services:
  api:
    build: ./backend
    container_name: travelhub-api
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/travelhub
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USERNAME: neo4j
      NEO4J_PASSWORD: password
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
      - neo4j

  mongo:
    image: mongo:6
    container_name: travelhub-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: travelhub-redis
    ports:
      - "6379:6379"

  neo4j:
    image: neo4j:5
    container_name: travelhub-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j-data:/data

volumes:
  mongo-data:
  neo4j-data:
