spring:
  application:
    name: travelhub
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
    redis:
      port: ${SPRING_REDIS_PORT}
      host: ${SPRING_REDIS_HOST}
neo4j:
  uri: ${NEO4J_URI}
  authentication:
    username: ${NEO4J_USERNAME}
    password: ${NEO4J_PASSWORD}